// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.25.1
// source: pkg/protobuf/order/order.proto

package order

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Save
type OrderSaveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    int64                       `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CompanyId int64                       `protobuf:"varint,4,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Products  []*OrderSaveRequest_Product `protobuf:"bytes,5,rep,name=products,proto3" json:"products,omitempty"`
}

func (x *OrderSaveRequest) Reset() {
	*x = OrderSaveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protobuf_order_order_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderSaveRequest) ProtoMessage() {}

func (x *OrderSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_order_order_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderSaveRequest.ProtoReflect.Descriptor instead.
func (*OrderSaveRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_order_order_proto_rawDescGZIP(), []int{0}
}

func (x *OrderSaveRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderSaveRequest) GetCompanyId() int64 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *OrderSaveRequest) GetProducts() []*OrderSaveRequest_Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type OrderSaveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Data   *OrderSaveResponse_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *OrderSaveResponse) Reset() {
	*x = OrderSaveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protobuf_order_order_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderSaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderSaveResponse) ProtoMessage() {}

func (x *OrderSaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_order_order_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderSaveResponse.ProtoReflect.Descriptor instead.
func (*OrderSaveResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_order_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrderSaveResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderSaveResponse) GetData() *OrderSaveResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// List User Orders
type ListUserOrdersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *ListUserOrdersRequest) Reset() {
	*x = ListUserOrdersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protobuf_order_order_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListUserOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserOrdersRequest) ProtoMessage() {}

func (x *ListUserOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_order_order_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListUserOrdersRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_order_order_proto_rawDescGZIP(), []int{2}
}

func (x *ListUserOrdersRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListUserOrdersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Orders []*ListUserOrdersResponse_Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
}

func (x *ListUserOrdersResponse) Reset() {
	*x = ListUserOrdersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protobuf_order_order_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListUserOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserOrdersResponse) ProtoMessage() {}

func (x *ListUserOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_order_order_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListUserOrdersResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_order_order_proto_rawDescGZIP(), []int{3}
}

func (x *ListUserOrdersResponse) GetOrders() []*ListUserOrdersResponse_Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type OrderSaveRequest_Product struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Quantity int64 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *OrderSaveRequest_Product) Reset() {
	*x = OrderSaveRequest_Product{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protobuf_order_order_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderSaveRequest_Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderSaveRequest_Product) ProtoMessage() {}

func (x *OrderSaveRequest_Product) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_order_order_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderSaveRequest_Product.ProtoReflect.Descriptor instead.
func (*OrderSaveRequest_Product) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_order_order_proto_rawDescGZIP(), []int{0, 0}
}

func (x *OrderSaveRequest_Product) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderSaveRequest_Product) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type OrderSaveResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string                            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId    int64                             `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CompanyId int64                             `protobuf:"varint,3,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Products  []*OrderSaveResponse_Data_Product `protobuf:"bytes,4,rep,name=products,proto3" json:"products,omitempty"`
}

func (x *OrderSaveResponse_Data) Reset() {
	*x = OrderSaveResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protobuf_order_order_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderSaveResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderSaveResponse_Data) ProtoMessage() {}

func (x *OrderSaveResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_order_order_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderSaveResponse_Data.ProtoReflect.Descriptor instead.
func (*OrderSaveResponse_Data) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_order_order_proto_rawDescGZIP(), []int{1, 0}
}

func (x *OrderSaveResponse_Data) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderSaveResponse_Data) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderSaveResponse_Data) GetCompanyId() int64 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *OrderSaveResponse_Data) GetProducts() []*OrderSaveResponse_Data_Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type OrderSaveResponse_Data_Product struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price    float64 `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Quantity int64   `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *OrderSaveResponse_Data_Product) Reset() {
	*x = OrderSaveResponse_Data_Product{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protobuf_order_order_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderSaveResponse_Data_Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderSaveResponse_Data_Product) ProtoMessage() {}

func (x *OrderSaveResponse_Data_Product) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_order_order_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderSaveResponse_Data_Product.ProtoReflect.Descriptor instead.
func (*OrderSaveResponse_Data_Product) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_order_order_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *OrderSaveResponse_Data_Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderSaveResponse_Data_Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderSaveResponse_Data_Product) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ListUserOrdersResponse_Product struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string  `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price       float64 `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Quantity    int64   `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *ListUserOrdersResponse_Product) Reset() {
	*x = ListUserOrdersResponse_Product{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protobuf_order_order_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListUserOrdersResponse_Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserOrdersResponse_Product) ProtoMessage() {}

func (x *ListUserOrdersResponse_Product) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_order_order_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserOrdersResponse_Product.ProtoReflect.Descriptor instead.
func (*ListUserOrdersResponse_Product) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_order_order_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ListUserOrdersResponse_Product) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListUserOrdersResponse_Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListUserOrdersResponse_Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ListUserOrdersResponse_Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ListUserOrdersResponse_Product) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ListUserOrdersResponse_Order struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string                            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Date     string                            `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Products []*ListUserOrdersResponse_Product `protobuf:"bytes,3,rep,name=products,proto3" json:"products,omitempty"`
}

func (x *ListUserOrdersResponse_Order) Reset() {
	*x = ListUserOrdersResponse_Order{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protobuf_order_order_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListUserOrdersResponse_Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserOrdersResponse_Order) ProtoMessage() {}

func (x *ListUserOrdersResponse_Order) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_order_order_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserOrdersResponse_Order.ProtoReflect.Descriptor instead.
func (*ListUserOrdersResponse_Order) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_order_order_proto_rawDescGZIP(), []int{3, 1}
}

func (x *ListUserOrdersResponse_Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListUserOrdersResponse_Order) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ListUserOrdersResponse_Order) GetProducts() []*ListUserOrdersResponse_Product {
	if x != nil {
		return x.Products
	}
	return nil
}

var File_pkg_protobuf_order_order_proto protoreflect.FileDescriptor

var file_pkg_protobuf_order_order_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x22, 0xbe, 0x01, 0x0a, 0x10, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79,
	0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x61,
	0x6e, 0x79, 0x49, 0x64, 0x12, 0x3b, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x73, 0x1a, 0x35, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0xc3, 0x02, 0x0a, 0x11, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x31, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0xe2, 0x01, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63,
	0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x64, 0x12, 0x41, 0x0a, 0x08, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x1a, 0x4f, 0x0a,
	0x07, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x30,
	0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x22, 0xc9, 0x02, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x06, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x52, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x1a, 0x81, 0x01, 0x0a, 0x07, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x1a, 0x6e, 0x0a, 0x05,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x41, 0x0a, 0x08, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x32, 0x9a, 0x01, 0x0a,
	0x0c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a,
	0x04, 0x53, 0x61, 0x76, 0x65, 0x12, 0x17, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18,
	0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x61, 0x76, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0c, 0x4c, 0x69,
	0x73, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x2e, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x16, 0x5a, 0x14, 0x2e, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_protobuf_order_order_proto_rawDescOnce sync.Once
	file_pkg_protobuf_order_order_proto_rawDescData = file_pkg_protobuf_order_order_proto_rawDesc
)

func file_pkg_protobuf_order_order_proto_rawDescGZIP() []byte {
	file_pkg_protobuf_order_order_proto_rawDescOnce.Do(func() {
		file_pkg_protobuf_order_order_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_protobuf_order_order_proto_rawDescData)
	})
	return file_pkg_protobuf_order_order_proto_rawDescData
}

var file_pkg_protobuf_order_order_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_protobuf_order_order_proto_goTypes = []interface{}{
	(*OrderSaveRequest)(nil),               // 0: order.OrderSaveRequest
	(*OrderSaveResponse)(nil),              // 1: order.OrderSaveResponse
	(*ListUserOrdersRequest)(nil),          // 2: order.ListUserOrdersRequest
	(*ListUserOrdersResponse)(nil),         // 3: order.ListUserOrdersResponse
	(*OrderSaveRequest_Product)(nil),       // 4: order.OrderSaveRequest.Product
	(*OrderSaveResponse_Data)(nil),         // 5: order.OrderSaveResponse.Data
	(*OrderSaveResponse_Data_Product)(nil), // 6: order.OrderSaveResponse.Data.Product
	(*ListUserOrdersResponse_Product)(nil), // 7: order.ListUserOrdersResponse.Product
	(*ListUserOrdersResponse_Order)(nil),   // 8: order.ListUserOrdersResponse.Order
}
var file_pkg_protobuf_order_order_proto_depIdxs = []int32{
	4, // 0: order.OrderSaveRequest.products:type_name -> order.OrderSaveRequest.Product
	5, // 1: order.OrderSaveResponse.data:type_name -> order.OrderSaveResponse.Data
	8, // 2: order.ListUserOrdersResponse.orders:type_name -> order.ListUserOrdersResponse.Order
	6, // 3: order.OrderSaveResponse.Data.products:type_name -> order.OrderSaveResponse.Data.Product
	7, // 4: order.ListUserOrdersResponse.Order.products:type_name -> order.ListUserOrdersResponse.Product
	0, // 5: order.OrderService.Save:input_type -> order.OrderSaveRequest
	2, // 6: order.OrderService.ListByUserId:input_type -> order.ListUserOrdersRequest
	1, // 7: order.OrderService.Save:output_type -> order.OrderSaveResponse
	3, // 8: order.OrderService.ListByUserId:output_type -> order.ListUserOrdersResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_protobuf_order_order_proto_init() }
func file_pkg_protobuf_order_order_proto_init() {
	if File_pkg_protobuf_order_order_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_protobuf_order_order_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderSaveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protobuf_order_order_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderSaveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protobuf_order_order_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListUserOrdersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protobuf_order_order_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListUserOrdersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protobuf_order_order_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderSaveRequest_Product); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protobuf_order_order_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderSaveResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protobuf_order_order_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderSaveResponse_Data_Product); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protobuf_order_order_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListUserOrdersResponse_Product); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protobuf_order_order_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListUserOrdersResponse_Order); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_protobuf_order_order_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_protobuf_order_order_proto_goTypes,
		DependencyIndexes: file_pkg_protobuf_order_order_proto_depIdxs,
		MessageInfos:      file_pkg_protobuf_order_order_proto_msgTypes,
	}.Build()
	File_pkg_protobuf_order_order_proto = out.File
	file_pkg_protobuf_order_order_proto_rawDesc = nil
	file_pkg_protobuf_order_order_proto_goTypes = nil
	file_pkg_protobuf_order_order_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderServiceClient interface {
	Save(ctx context.Context, in *OrderSaveRequest, opts ...grpc.CallOption) (*OrderSaveResponse, error)
	ListByUserId(ctx context.Context, in *ListUserOrdersRequest, opts ...grpc.CallOption) (*ListUserOrdersResponse, error)
}

type orderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderServiceClient(cc grpc.ClientConnInterface) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) Save(ctx context.Context, in *OrderSaveRequest, opts ...grpc.CallOption) (*OrderSaveResponse, error) {
	out := new(OrderSaveResponse)
	err := c.cc.Invoke(ctx, "/order.OrderService/Save", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) ListByUserId(ctx context.Context, in *ListUserOrdersRequest, opts ...grpc.CallOption) (*ListUserOrdersResponse, error) {
	out := new(ListUserOrdersResponse)
	err := c.cc.Invoke(ctx, "/order.OrderService/ListByUserId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
type OrderServiceServer interface {
	Save(context.Context, *OrderSaveRequest) (*OrderSaveResponse, error)
	ListByUserId(context.Context, *ListUserOrdersRequest) (*ListUserOrdersResponse, error)
}

// UnimplementedOrderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOrderServiceServer struct {
}

func (*UnimplementedOrderServiceServer) Save(context.Context, *OrderSaveRequest) (*OrderSaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Save not implemented")
}
func (*UnimplementedOrderServiceServer) ListByUserId(context.Context, *ListUserOrdersRequest) (*ListUserOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListByUserId not implemented")
}

func RegisterOrderServiceServer(s *grpc.Server, srv OrderServiceServer) {
	s.RegisterService(&_OrderService_serviceDesc, srv)
}

func _OrderService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderSaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/Save",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).Save(ctx, req.(*OrderSaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_ListByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).ListByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/ListByUserId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).ListByUserId(ctx, req.(*ListUserOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "order.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Save",
			Handler:    _OrderService_Save_Handler,
		},
		{
			MethodName: "ListByUserId",
			Handler:    _OrderService_ListByUserId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/protobuf/order/order.proto",
}
